---
title: "Literature Review"
author: "Holly Bernesser"
date: "Thursday, January 29, 2015"
output: html_document
bibliography: GapminderBib.bib
nocite: |
 @bin_consumer_2005, @helsper_gendered_2010, @dhakal_urban_2009
---

# Gapminder

With the topic that I have decided to focus on, I will use certain terms like _The Digital Divide_, _Data Centers_, _energy use_, and _emissions_.  After I read through many different titles and abstracts I have found that there is a lot of attention to the growth of energy use over the past couple decades.  I am mostly interrested in the connections between energy use - especially with the internet - and co2 emissions.  There is also a stong connection to income and wealth.  I focus mostly on the energy use, co2 emissions and income across the world and then comparing to see what connections there are.



Based on what I have read from the aboce articles, I noticed a few interresting points:

@chinn_determinants_2004, says that public investment in things like human captial and different types of regulations can help bridge the gap in PC and Internet Use.  A few more people investing in the public's wellbeing can help more people have access to computers and the internet.

@lynch_income_2000, speaks about how differences in income are generally related to health conditions. Health is also generally related to the wealth of a country.

@koomey_worldwide_2008, Talk about when there was a large increase of energy use from data centers in 2000-2005.  A lot of the increase was found to be from the least expensive of the data centers as well.

@schipper_evolution_1997, says that CO2 emissions also seem to correspond to high energy uses. CO2 emissions are expected to continue to rise unless something is done about the excessive energy use across the world.

I have decided to further focus my question on how energy use (including internet use) effects co2 emissions.  I would like to focus primarily on Europe, the United States and Asia. I am curious as to whether or not more industriallized countries like China have higher energy use and therefore internet use than countries that are less industrialized.  China is often viewed as the industrial center and the US as the country that buys their products.  I want to see the connection between energy use (internet) and co2 emission from these three different areas.

I will add various demographic variables such has what type of cars are prominent, population and location (City, Urban, Rural).  I will also ask relevant questions about energy use and co2 emission to my own personal code book.

# References